[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11>=2.8.0",
    "conan",
    "scikit-build>=0.12",
]

build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
